FROM golang as builder

RUN mkdir -p /go/src/github.com/sebastienmusso/infradatamgmt
WORKDIR /go/src/github.com/sebastienmusso/infradatamgmt
COPY . .
RUN go get -v
RUN go build -o surikat

FROM ubuntu
WORKDIR /root
COPY --from=builder /go/src/github.com/sebastienmusso/infradatamgmt/surikat .
CMD ["./surikat"]
